r485: Improved compiling - now correctly reports an error if the file doesn't compile. If configure is missing then autoconf is run automatically.

diff --git a/ROX-Filer/AppRun b/ROX-Filer/AppRun
--- a/ROX-Filer/AppRun
+++ b/ROX-Filer/AppRun
@@ -22,32 +22,34 @@ case $1 in
 			exit 1
 		fi
 		echo "Compiling $APP_DIR... please wait..." >&2
+		if [ ! -x "$APP_DIR/src/configure" ]; then
+		  echo "No 'configure' script! Trying to run autoconf..."
+		  (cd $APP_DIR/src; autoconf)
+		fi
 		rm -f $APP_DIR/src/config.cache
 		cd $APP_DIR/src && ./configure --bindir=$APP_DIR/$PLATFORM \
 			&& make clean && make && echo Done >&2 && exit 0
 		echo Compile failed >&2
+		echo Press Return... >&2
+		read WAIT
 		exit 1
 esac
 
 BIN=$APP_DIR/$PLATFORM/$PROG
 
-if [ -x $BIN ] ; then
+if [ -x $BIN ]; then
   exec $DEBUGGER $BIN "$@"
 else
+  echo "ERROR from $0:" >&2
+  echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
+  echo "Trying to compile..." >&2
   if [ -n "$DISPLAY" ]; then
-    xmessage -buttons Compile:1,Abort:0 -file - << EOF
-$APP_DIR:
-I cannot find an executable file for your host type ($PLATFORM).
-Try to compile from source?
-EOF
-    if [ "$?" -eq 0 ]; then
-      exit 0
-    fi
-    exec xterm -e "$0" --compile
+    xterm -e $0 --compile
   else
-    echo "ERROR from $0:" >&2
-    echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
-    echo "Try using the --compile option." >&2
+    $0 --compile
   fi
+  if [ -x $BIN ]; then
+    exec $BIN "$@"
+  fi
+  exit 1
 fi
-exit 1
