r431: Attempting to run the filer before compiling will now ask if you want to compile. Removed lots of platform-specific mount point code and replaced it with python's portable system. New options section allows you to choose a translation without having to set the LANG variable.

diff --git a/ROX-Filer/AppRun b/ROX-Filer/AppRun
--- a/ROX-Filer/AppRun
+++ b/ROX-Filer/AppRun
@@ -34,8 +34,20 @@ BIN=$APP_DIR/$PLATFORM/$PROG
 if [ -x $BIN ] ; then
   exec $DEBUGGER $BIN "$@"
 else
-  echo "ERROR from $0:" >&2
-  echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
-  echo "Try using the --compile option." >&2
-  exit 1
+  if [ -n "$DISPLAY" ]; then
+    xmessage -buttons Compile:1,Abort:0 -file - << EOF
+$APP_DIR:
+I cannot find an executable file for your host type ($PLATFORM).
+Try to compile from source?
+EOF
+    if [ "$?" -eq 0 ]; then
+      exit 0
+    fi
+    exec xterm -e "$0" --compile
+  else
+    echo "ERROR from $0:" >&2
+    echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
+    echo "Try using the --compile option." >&2
+  fi
 fi
+exit 1
